### Task 1: A list of dictionaries (1p)

You are given a list of raw transaction records, where each record is a dictionary:

transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

Write a script that performs the following steps:

In [3]:
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

a) Filter out invalid transactions where the price is zero or the quantity is negative.

In [17]:
# use the filter function in python to filter out invalid transactions, and using lambda function filter specify what to filter out
filtered_transactions = list(filter(lambda transaction : transaction['price'] > 0 and transaction['quantity'] >= 0, transactions))
print(filtered_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]

b) For each remaining transaction, compute a new field total = price * quantity.

In [11]:
for i in filtered_transactions:
    i["total"] = i["price"] * i["quantity"]
print(filtered_transactions)

[{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}, {'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}, {'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}, {'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}]

c) Group the valid transactions by region and compute the total revenue per region. Store the result in a dictionary.

In [15]:
region_revenue = {}
# loop through and add to the region dictionary
for i in filtered_transactions:
    region = i["region"]
    rev = i["total"]
    region_revenue[region] = rev + region_revenue.get(region, 0)
print(region_revenue)

{'EU': 3600, 'US': 1050, 'APAC': 750}

d) Print the region with the highest total revenue and its value using an f-string.

In [24]:
# change region_revenue to a list of tuples for easier processing, use lambda function to filter by the revenue
highest_rev_region = max(region_revenue.items(), key = lambda regrev: regrev[1] )
print(f'Region with the highest total revenue is {highest_rev_region[0]} with a value of ${highest_rev_region[1]}')

Region with the highest total revenue is EU with a value of $3600

### Task 2: Creating a function (1p)

You are given the following list of daily sales figures (in euros) for a two-week period:

sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

Write a function called summarise_sales that takes a list of daily sales values and returns a dictionary containing:

"total": the sum of all daily sales

"average": the mean daily sales value, rounded to two decimals

"best_day": the index (starting from 1) of the day with the highest sales

"worst_day": the index (starting from 1) of the day with the lowest sales

"above_average_count": the number of days where sales exceeded the average

Call the function with the list above and print the returned dictionary.

In [28]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

def summarise_sales(sales_list):
    total = sum(sales_list)
    # question ask for rounding to 2 decimal place
    average = round(total/len(sales_list), 2)
    # both need to add one so as the question states that the index starts from one
    best_day = max(range(len(sales_list)), key = lambda idx: sales_list[idx]) + 1
    worst_day = min(range(len(sales_list)), key = lambda idx: sales_list[idx]) + 1
    above_average_count = sum(1 for x in sales_list if x > average)
    return {'total':total, 'average':average, 'best_day':best_day, 'worst_day':worst_day, 'above_average_count':above_average_count}
    
print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}

### Task 3: Loops (1p)

You are given the following list of student records:

students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

Using for loops and if statements, perform the following:

In [29]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

a) Create a new list called passing that contains only the names of students with a grade of 50 or above. Print the list.

In [31]:
# passing = [x for x in students if x["grade"] >= 50]
passing = []
for i in students:
    if i["grade"] >=50:
        passing.append(i)
print(passing)

[{'name': 'Anna', 'grade': 85, 'attendance': 0.92}, {'name': 'Erik', 'grade': 58, 'attendance': 0.75}, {'name': 'Mia', 'grade': 91, 'attendance': 0.98}, {'name': 'Sara', 'grade': 72, 'attendance': 0.88}, {'name': 'Tom', 'grade': 67, 'attendance': 0.7}, {'name': 'Nina', 'grade': 95, 'attendance': 0.99}, {'name': 'Olli', 'grade': 50, 'attendance': 0.65}]

b) Loop through the students and print a status message for each. If the student's grade is 80 or above, print "[name]: Excellent"; if between 50 and 79, print "[name]: Pass"; otherwise print "[name]: Fail".

In [32]:
for i in students:
    name = i["name"]
    grade = i['grade']
    if grade >=80:
        print(f'[{name}]: Excellent')
    elif 50 <= grade <= 79:
        print(f'[{name}]: Pass')
    else:
        print(f'[{name}]: Fail')

[Anna]: Excellent
[Erik]: Pass
[Mia]: Excellent
[Leo]: Fail
[Sara]: Pass
[Tom]: Pass
[Nina]: Excellent
[Olli]: Pass

c) Count how many students have an attendance rate below 0.80. Print the count.

In [34]:
# print(sum(1 for x in students if x["attendance"] < 0.8))
count = 0
for i in students:
    if i["attendance"] < 0.8:
        count += 1
print(count)

4

d) Find the student with the highest grade using a loop (do not use max()). Print the student's name and grade.

In [35]:
name = ''
grade = 0
for i in students:
    temp_name = i['name']
    temp_grade = i['grade']
    if temp_grade > grade:
        grade = temp_grade
        name = temp_name
print(f'name: {name}, grade: {grade}')

name: Nina, grade: 95

e) Now find the student with the highest grade using max(). Print the student's name and grade.

In [42]:
student_highest = max(students, key = lambda student: student['grade'])
print(f'name: {student_highest["name"]}, grade: {student_highest["grade"]}')

name: Nina, grade: 95

Task 4: Class and methods (1p)

Design a class called Portfolio that represents an investment portfolio. The constructor is provided for you:

class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

Each key in holdings is a ticker symbol (string) and each value is a dictionary with keys "shares" and "price_per_share". Add the following methods to the class:
Task 4: Class and methods (1p)

Design a class called Portfolio that represents an investment portfolio. The constructor is provided for you:

class Portfolio:
    <br>def __init__(self, owner):
    <br>    self.owner = owner
    <br>    self.holdings = {}  # ticker -> {shares, price_per_share}

Each key in holdings is a ticker symbol (string) and each value is a dictionary with keys "shares" and "price_per_share". Add the following methods to the class:

a) A method add_asset(ticker, shares, price_per_share) that adds a new asset or updates the number of shares if the ticker already exists (in which case the price should also be updated).

b) A method total_value() that returns the total market value of the portfolio.

c) A method most_valuable() that returns the ticker of the asset with the highest total value (shares × price).

d) A __str__ method that returns a readable summary of the portfolio, including the owner's name, the number of assets, and the total value.

Create an instance, add at least three assets, and demonstrate all methods with printed output.

In [57]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}
    
    # a
    def add_asset(self, ticker, shares, price_per_share):
        if ticker in self.holdings:
            update = self.holdings[ticker]
            update['shares'] += shares
            update['price_per_share'] = price_per_share
        else:
            self.holdings[ticker] = {'shares':shares, 'price_per_share':price_per_share}
       
    #b     
    def total_value(self):
        total = 0
        for value in self.holdings.values():
            total += value['shares'] * value['price_per_share']
        return total
    
    #c
    def most_valuable(self):
        return max(self.holdings, key = lambda holding: self.holdings[holding]['shares'] * self.holdings[holding]['price_per_share'])
        
    #d
    def __str__(self):
        return f'owner: {self.owner}, number of assets: {len(self.holdings)}, total value: {self.total_value()}'

In [58]:
# testing adding 3 assets
portfolio1 = Portfolio('name')
portfolio1.add_asset('AAA', 10, 1000)
print(portfolio1)
portfolio1.add_asset('BBB', 20, 100)
print(portfolio1)
portfolio1.add_asset('CCC', 10, 10)
print(portfolio1)

# testing add asset with ticker already inside
portfolio1.add_asset('AAA', 10, 1000)
print(portfolio1)
# testing add asset with ticker already inside but with different price per share
portfolio1.add_asset('CCC', 8, 1)
print(portfolio1)

# test total_value()
print(portfolio1.total_value())

# test most_valuable
print(portfolio1.most_valuable())

owner: name, number of assets: 1, total value: 10000
owner: name, number of assets: 2, total value: 12000
owner: name, number of assets: 3, total value: 12100
owner: name, number of assets: 3, total value: 22100
owner: name, number of assets: 3, total value: 22018
22018
AAA

### Task 5: Importing a module (1p)

You are given the following list of order dates (as strings) and product names:

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

Using the datetime module, parse each date string into a datetime.date object. Compute and print the number of days between the earliest and latest order.

In [66]:
import datetime as dt

orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

# n = len(orders)
# for i in range(n):
#     current = orders[i]
#     date_list = current[0].split('-')
#     year = int(date_list[0])
#     month = int(date_list[1])
#     day = int(date_list[2])
#     current_date = dt.date(year, month, day)
#     orders[i] = (current_date, current[1])
    
# for testing
# print(orders)

alldates = [dt.date.fromisoformat(order[0]) for order in orders]
print(max(alldates) - min(alldates))

80 days, 0:00:00

### Task 6: Array Operations and Broadcasting (1p)

A company tracks quarterly revenue (in thousands of euros) across four quarters over three years:

In [68]:
import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

a) Compute and print the total annual revenue for each year (i.e., row sums). Use the axis parameter.

In [69]:
total_rev = np.sum(revenue, axis = 1)
print(total_rev)

[ 880  950 1080]

b) Compute the mean quarterly revenue across all years (i.e., column means).

In [70]:
avg_quarter_rev = np.mean(revenue, axis = 0)
print(avg_quarter_rev)

[226.66666667 260.         206.66666667 276.66666667]

c) Using broadcasting, apply a growth adjustment to the 2024 row by multiplying it element-wise with the array [1.05, 1.03, 1.08, 1.02]. Print the adjusted values.

In [76]:
revenue[2] = (revenue[2] * [1.05, 1.03, 1.08, 1.02]).astype('float64')
print(revenue)

[[210 230 190 250]
 [220 260 200 270]
 [288 315 288 328]]

d) Use boolean indexing to find and print all quarterly revenue values that exceed 250 (thousands of euros).

In [77]:
print(revenue[revenue > 250])

[260 270 288 315 288 328]

### Task 7: Pandas (1p)

Create the following DataFrame:

In [107]:
import pandas as pd

data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}

df = pd.DataFrame(data)
print(df)

  employee department  salary  years_exp  performance_score
0     Anna    Finance    4500          5                4.2
1     Erik  Marketing    4000          3                3.8
2      Mia    Finance    4800          7                4.5
3      Leo         IT    5200         10                4.0
4     Sara  Marketing    3900          2                3.5
5      Tom         IT    5100          8                4.9

a) Add a new column salary_per_year_exp computed as salary / years_exp. Round to the nearest integer.

In [108]:
df['salary_per_year_exp'] = round(df['salary'] / df['years_exp'], 0).astype('int32')

b) Sort the DataFrame by performance_score in descending order and print the top 3 employees.

In [109]:
df.sort_values('performance_score', ascending = False)
df.head(3)

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900
1,Erik,Marketing,4000,3,3.8,1333
2,Mia,Finance,4800,7,4.5,686

c) Using .loc, select all employees in the Finance department with a performance score above 4.0. Print the result.

In [110]:
df.loc[(df['department'] == 'Finance') & (df['performance_score'] > 4.0)]

,employee,department,salary,years_exp,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900
2,Mia,Finance,4800,7,4.5,686

d) Rename the column years_exp to experience_years using the .rename() method.

In [111]:
df.rename(columns = {'years_exp':'experience_years'})

,employee,department,salary,experience_years,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900
1,Erik,Marketing,4000,3,3.8,1333
2,Mia,Finance,4800,7,4.5,686
3,Leo,IT,5200,10,4.0,520
4,Sara,Marketing,3900,2,3.5,1950
5,Tom,IT,5100,8,4.9,638

e) Using .iloc, select and print the salary and performance score columns for the first four employees.

In [112]:
df.iloc[:4, [2,4]]

   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0

### Task 8: More Pandas (1p)

A company records daily website traffic over four weeks. Generate the data by running the following script first:

In [99]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

a) Create a DataFrame with columns: date, visitors, conversion_rate, and avg_order_value. Set date as the index.

In [103]:
df = pd.DataFrame({'date':days, 'visitors':visitors, 'conversion_rate':conversion_rate, 
                   'avg_order_value':avg_order_value})
df.set_index('date', inplace=True)
df.head()

            visitors  conversion_rate  avg_order_value
date
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39

b) Compute two new columns: conversions (= visitors × conversion_rate, rounded to the nearest integer) and daily_revenue (= conversions × avg_order_value).

In [105]:
df['conversions'] = round(df['visitors'] * df['conversion_rate'], 0).astype('int32')
df['daily_revenue'] = df['conversions'] * df['avg_order_value']
df.head()

,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
date,,,,,
2025-01-06,206,0.0645,64.30,13,835.90
2025-01-07,472,0.0578,48.44,27,1307.88
2025-01-08,437,0.0756,43.26,33,1427.58
2025-01-09,221,0.0339,43.61,7,305.27
2025-01-10,563,0.0679,49.39,38,1876.82